language: ruby
rvm:
  - 2.3.0
  - 2.2.2
gemfile:
  - Gemfile
services:
  - mongodb
install: bundle install
before_script:
  - mongo --eval "db.adminCommand({ setParameter: true, textSearchEnabled : true})"
  - RAILS_ENV=test rake db:mongoid:create_indexes
  - sleep 5
script: bundle exec rspec
