language: ruby
rvm:
  - 2.3.0
  - 2.2.2
gemfile:
  - Gemfile
services:
  - mongodb
install: bundle install
before_script:
  - ./init_mongo.sh
  - RAILS_ENV=test rake db:mongoid:create_indexes
  - sleep 5
script: bundle exec rspec
