version: '2'
services:
  mongo:
    image: mongo:3.2.4
    volumes:
      - /data/db
    ports:
      - "27017:27017"
    command: --smallfiles
  kip:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: production
      MONGODB_IP: mongo
      RAILS_SERVE_STATIC_FILES: 'yes'
    env_file:
      - ./config/secrets.env
    ports:
      - "3001:3000"
    depends_on:
      - mongo
